### ISSUE TITLE
Cannot add more than two item in Submenu

### ISSUE THREAD

**Issue by darkiron** [KnpLabs/KnpMenu#276] opened 2017-10-10 10:15 UTC
Hi, I try to add one more item in my submenu in Sylius admin by Service. 

http://docs.sylius.org/en/latest/customization/menu.html#url

```php
$newSubmenu
            ->addChild('new-subitem',['route' => 'XX'])
            ->setLabel('XX')
            ->setName('toto');

        $newSubmenu
            ->addChild('hhh',['route' => 'XX2'])
            ->setLabel('XX 2')
            ->setName('tata');
```

But I have only one. You can help-me ?

**Comment by stof** [comment] 2017-10-10 10:22
Can you provide a reproducing case ? I'm using KnpMenu since years, and I definitely have multiple children by menu item.
and if this cannot be reproduced outside Sylius, it would be best to report this to Sylius.

**Comment by darkiron** [comment] 2017-10-10 13:06
I finde a solution : 
```
public function addAdminMenuItems(MenuBuilderEvent $event){
        $menu = $event->getMenu();
        $factory = $event->getFactory();

        $newSubmenu = $menu
            ->addChild('new')
            ->setLabel('xx')
            ->setName('xx.xx')
        ;

        $items[] = 
            $factory->createItem('xx.xx',['route' => 'xx'] )
                    ->setLabel('xx xx xx')
        ;
        $items[] = 
            $factory->createItem('xx.xx',['route' => 'xx'])
                    ->setLabel('xx xx')
        ;
    
       $newSubmenu->setChildren($items);
    }
```
Before child is not erase by the last.

**Comment by stof** [comment] 2018-04-10 16:45
I'm closing this, as a reproducing case (independent from Sylius) was not provided

**Closed by stof** 2018-04-10 16:45 UTC
