### ISSUE TITLE
Basic Documentation very out of date

### ISSUE THREAD

**Issue by mcgoode** [KnpLabs/KnpMenu#290] opened 2018-04-09 20:19 UTC
[Basic Documentation](https://github.com/KnpLabs/KnpMenu/blob/master/doc/01-Basic-Menus.markdown#creating-a-menu-from-a-tree-structure) has [deprecated information](https://github.com/KnpLabs/KnpMenu/blob/master/CHANGELOG.md#200-alpha-2-2014-05-01) from many years ago. Please consider updating or removing this section. It confused me for a bit until I saw the change log.

**Comment by stof** [comment] 2018-04-10 16:17
This section should be updated to use the new APIs (and this probably does not belong to the basic doc, as it is a more advanced used case).

**Comment by stof** [comment] 2018-04-10 16:42
Closing as duplicate of #277

**Closed by stof** 2018-04-10 16:42 UTC
Labels: Doc, good first issue
