### ISSUE TITLE
Composer update - Circular reference detected for service "knp_menu.matcher"

### ISSUE THREAD

**Issue by Ashallar** [KnpLabs/KnpMenu#285] opened 2018-02-09 09:31 UTC
Hi,

i've been trying to install an existing symfony solution on my laptop, but i've been struggling with a circular reference for a while.

So once my solution was on my laptop i executed a 'composer update' to update all bundles of the solution but the update fails with that error:

```
Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]
Circular reference detected for service "knp_menu.matcher", path: "knp_menu.matcher -> sonata.admin.menu.matcher.voter.children -> knp_menu.matcher".

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

[RuntimeException]
An error occurred when executing the ""cache:clear --no-warmup"" command:

[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]
Circular reference detected for service "knp_menu.matcher", path: "knp_menu.matcher -> sonata.admin.menu.matcher.voter.children -> knp_menu.matcher".
```
Here's what's in my composer.json:

```
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.1.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "doctrine/doctrine-migrations-bundle": "^1.2",
        "sonata-project/admin-bundle": "^3.5",
        "sonata-project/doctrine-orm-admin-bundle": "^3.0",
        "symfony/assetic-bundle": "^2.8",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "craue/formflow-bundle": "~3.0@dev",
        "vich/uploader-bundle": "^1.3",
        "knplabs/knp-paginator-bundle": "^2.5",
        "jms/serializer-bundle": "^1.1",
        "liip/imagine-bundle": "^1.6",
        "ancarebeca/full-calendar-bundle": "^3.0",
        "adesigns/calendar-bundle": "^1.1",
        "sllh/iso-codes-validator": "^3.0",
        "beberlei/DoctrineExtensions": "^1.0",
        "dompdf/dompdf": "^0.8.0",
        "friendsofsymfony/rest-bundle": "^2.2",
        "snilius/twig-sort-by-field": "^0.1.5"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    }
```

If i understand correctly the problem (i'm new to symfony):

knp_menu.matcher references sonata.... which itself references knp_menu.matcher, which end-up throwing that circular reference error.

Do you have any clue how to fix this ?

Best regards, Bastien.

**Comment by stof** [comment] 2018-02-09 09:45
closing as duplicate of https://github.com/KnpLabs/KnpMenu/issues/281 and https://github.com/KnpLabs/KnpMenuBundle/issues/366

This is a bug in SonataAdminBundle, which has been fixed in their 3.28.0 release. Make sure you use an uptodate version of SonataAdminBundle

**Closed by stof** 2018-02-09 09:45 UTC

**Comment by Ashallar** [comment] 2018-02-09 10:10
Hi,

i think i have the latest package of sonata (3.5) as it is written on my composer.json
`"sonata-project/admin-bundle": "^3.5",`
though i still have the issue..

**Comment by stof** [comment] 2018-02-09 11:29
what is written in your composer.json does not tell me what gets installed, as it shows version ranges (`^3.5` allows to use any release between 3.5 and the latest 3.31, so it does not tell me whether you are above 3.28 or no).

Use `composer show -i` to list the *installed* versions of packages.
